version: "3"
services:
  pihole:
    image: diginc/pi-hole:arm_v3.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      # enter your docker host IP here
      ServerIP: ${IP}
      WEBPASSWORD: ${PASS}
    volumes:
      - "${HOME}/etc/:/etc/pihole/"
      - "${HOME}/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    restart: always




