version: 2
volumes:
  resin-data:
services:
  pihole:
    image: pihole/pihole:latest
    volumes:
      - "${PWD}/pihole/:/etc/pihole/"
      - "${PWD}/dnsmasq.d/:/etc/dnsmasq.d/"
    ports:
      - "80:80"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "443:443"
    privileged: true
    restart: always


